defaults:
    - _self_
    - datamodule: null
    - model: null
    - trainer: null
    - callback: default
    - experiments: null

seed: 42
result_dir: "./results"
name: null
version: null

hydra:
    run:
        dir: ${result_dir}/${name}/${version}
